spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/spring-qna-db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mustache:
    suffix: .html
    cache: false
    expose-session-attributes: true

server:
  servlet:
    encoding:
      force: true
    session:
      tracking-modes: cookie
