spring:
  profiles:
    active: prod

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mustache:
    suffix: .html
    cache: false
    expose-session-attributes: true

server:
  servlet:
    encoding:
      force: true
    session:
      tracking-modes: cookie
